openapi: 3.0.0

info:
  title: "Swiss QR Bill API"
  description: |
    The Swiss QR Bill API for generating the new payment slip for invoices. The QR code contains
    the complete payment information in a machine-readable form:

    - Payment amount and currency
    - Creditor address and account
    - Final creditor address (if needed)
    - Reference number issued by the creditor
    - Additional informationn for the recipient of the invoice
    - Debtor address
    - Due date (optional)

    Debtor and amount can be omitted and filled in by the payer.

    The QR bill payment part can be generated as an A6, A5 or A4 sheet. Alternatively, the QR code only can be generated.
    Supported formats are SVG and PDF.

    To successfully validate the bill data and generate a QR bill, the following main requirements must be met:

    - A valid address must at least contain *name*, *postal code*, *town* and *country ISO code*.
    - The creditor address and accout number are mandatory.
    - The final creditor and the debtor addresses are optional. If they are not used, they must be omitted entirely
      or all address fields must be *null* or empty.
    - The account number must be a valid IBAN of Switzerland or Liechtenstein.
    - If a reference number is provided, it must be either a valid QR/ISR reference number
      or a valid ISO 11649 creditor reference (i.e. the applicable check digits must be valid)
    - The currency must be either *CHF* or *EUR*.

    If fields are too long, they are automaticalluy truncated. If characters outside the restricted range of
    characters are used, they are automatically replaced. The validation result contains warnings about
    truncations and replacements.

  version: 1.0.1
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"

servers:
- url: "https://www.codecrete.net/qrbill-api"

tags:
- name: bills
  description: "Generate and validate QR bills"

paths:
  /bill/validate:
    post:
      tags:
      - bills
      summary: "Validate the data for a QR bill"
      description: "Validates the data for a QR bill. The result contains a list of errors (if any), a bill ID (if the data is valid) and the possibly modified bill data."
      operationId: validateBill
      requestBody:
        required: true
        description: "Bill data to be validated"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrBill"
      responses:
        '200':
          description: "Validation result"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationResponse"

  /bill/svg/{outputSize}:
    post:
      tags:
      - bills
      summary: "Generates QR bill as SVG"
      operationId: "generateBillAsSVG"
      parameters:
      - in: path
        name: outputSize
        description: "The output size of the generated QR bill (or QR code)"
        required: true
        schema:
          type: string
          enum:
          - "a6-landscape"
          - "a5-landscape"
          - "a4-portrait"
          - "qr-code-only"
      requestBody:
        required: true
        description: "Bill data"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrBill"
      responses:
        '200':
          description: "QR bill as SVG"
          content:
            image/svg+xml:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/pdf/{outputSize}:
    post:
      tags:
      - bills
      summary: "Generates QR bill as PDF"
      operationId: generateBillAsPDF
      parameters:
      - in: path
        name: outputSize
        description: "The output size of the generated QR bill (or QR code)"
        required: true
        schema:
          type: string
          enum:
          - "a6-landscape"
          - "a5-landscape"
          - "a4-portrait"
          - "qr-code-only"
      requestBody:
        description: "Bill data"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrBill"
      responses:
        '200':
          description: "QR bill as PDF"
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/svg/{outputSize}/{billID}:
    get:
      tags:
      - bills
      summary: "Generates QR bill as SVG"
      operationId: getBillAsSVG
      parameters:
      - in: path
        name: outputSize
        description: "The output size of the generated QR bill (or QR code)"
        required: true
        schema:
          type: string
          enum:
          - "a6-landscape"
          - "a5-landscape"
          - "a4-portrait"
          - "qr-code-only"
      - in: path
        name: billID
        description: "Bill ID as returned by the validation response. Specifies the QR bill data uniquely."
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "QR bill as SVG"
          content:
            image/svg+xml:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/pdf/{outputSize}/{billID}:
    get:
      tags:
      - bills
      summary: "Generates QR bill as PDF"
      operationId: getBillAsPDF
      parameters:
      - in: path
        name: outputSize
        description: "The output size of the generated QR bill (or QR code)"
        required: true
        schema:
          type: string
          enum:
          - "a6-landscape"
          - "a5-landscape"
          - "a4-portrait"
          - "qr-code-only"
      - in: path
        name: billID
        description: "Bill ID as returned by the validation response. Specifies the QR bill data uniquely."
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "QR bill as SVG"
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/decode:
    post:
      tags:
      - bills
      summary: "Decode the text embedded in the QR code"
      operationId: decodeQRCode
      requestBody:
      requestBody:
        description: "QR code information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrCodeInformation"
      responses:
        '200':
          description: "Validation result (incl. bill data)"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationResponse"

components:
  schemas:

    Address:
      type: object
      properties:
        name:
          type: string
          description: "First, middle and last name of a natural person or company or organization name of a legal person"
        street:
          type: string
          description: "Street name (without the house number)"
        houseNo:
          type: string
          description: "House or building number"
        town:
          type: string
          description: "Town or city name"
        postalCode:
          type: string
          description: "Postal code"
        countryCode:
          type: string
          description: "Two letter ISO country code"

    QrBill:
      type: object
      properties:
        language:
          type: string
          description: "Language of the generated QR bill"
          enum:
          - "de"
          - "fr"
          - "it"
          - "en"
        version:
          type: string
          description: "QR bill specification version"
          default: "V1_0"
        amount:
          type: number
          description: "Bill amount"
        currency:
          type: string
          default: "CHF"
          description: "Bill currency"
        account:
          type: string
          description: "Creditor's account"
        creditor:
          $ref: "#/components/schemas/Address"
        finalCreditor:
          $ref: "#/components/schemas/Address"
        referenceNo:
          type: string
          description: "Payment reference number (QR/ISR reference number or ISO 11649 creditor reference)"
        additionalInfo:
          type: string
          description: "Additional information for the bill recipient"
        debtor:
          $ref: "#/components/schemas/Address"
        dueDate:
          type: string
          description: "Payment due date"
          format: date

    ValidationMessage:
      type: object
      properties:
        type:
          type: string
          description: "Message type (error or warning)"
          enum:
          - "Error"
          - "Warning"
        messageKey:
          type: string
          description: "Language independent message key"
        messageParameters:
          type: array
          description: "Variable parts of the message (if any)"
          items:
            type: string
        message:
          type: string
          description: "Localized message (incl. variable parts). The Accept-Language header field is used to select a suitable language."
        field:
          type: string
          description: "Affected field name. Examples are Examples are: \"account\", \"creditor.street\""

    ValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: "Indicates if the bill data was valid or not"
        validationMessages:
          type: array
          items:
            $ref: "#/components/schemas/ValidationMessage"
        validatedBill:
          $ref: "#/components/schemas/QrBill"
        billID:
          type: string
          description: "Bill ID if the bill data was valid. Used to retrieve the QR bill as SVG or PDF."
        qrCodeText:
          type: string
          description: "Text embedded in QR code if the bill data was valid."

    QrCodeInformation:
      type: object
      properties:
        text:
          type: string
          description: "QR code text"

externalDocs:
  description: "Find out more about Swiss QR Bill"
  url: "https://github.com/manuelbl/SwissQRBill"
