name: Continuous Integration

on: [push, pull_request]

env:
  Configuration: Release
  ContinuousIntegrationBuild: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        working-directory: ./generator
        run: ./gradlew jar javadoc -PossrhUsername=nobody -PossrhPassword=removed
      - name: SonarQube
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        working-directory: ./generator
        run: ./gradlew sonarqube -PossrhUsername=nobody -PossrhPassword=removed -Dsonar.organization=manuelbl-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
